// ============================================================
// Dashboard block types — dynamic UI blocks generated by chat
// ============================================================

import type { TrendDirection } from "./metrics";

// --- Block type union ---

export type DashboardBlockType =
  | "kpi_grid"
  | "line_chart"
  | "bar_chart"
  | "donut_chart"
  | "table"
  | "comparison"
  | "alert"
  | "text_summary";

// --- KPI Grid ---

export interface KPIItem {
  label: string;
  value: string;
  previousValue?: string;
  trend?: string;
  trendDirection?: TrendDirection;
  icon?: string;
  color?: "default" | "success" | "warning" | "danger";
}

export interface KPIGridBlock {
  type: "kpi_grid";
  items: KPIItem[];
}

// --- Charts ---

export interface ChartSeries {
  key: string;
  label: string;
  color?: string;
}

export interface LineChartBlock {
  type: "line_chart";
  title?: string;
  xAxisKey: string;
  series: ChartSeries[];
  data: Record<string, unknown>[];
}

export interface BarChartBlock {
  type: "bar_chart";
  title?: string;
  xAxisKey: string;
  series: ChartSeries[];
  data: Record<string, unknown>[];
}

export interface DonutChartBlock {
  type: "donut_chart";
  title?: string;
  data: {
    label: string;
    value: number;
    color?: string;
  }[];
}

// --- Table ---

export type ColumnFormat = "currency" | "percent" | "number" | "text";

export interface TableColumn {
  key: string;
  label: string;
  format?: ColumnFormat;
}

export interface TableBlock {
  type: "table";
  title?: string;
  columns: TableColumn[];
  rows: Record<string, unknown>[];
  sortable?: boolean;
}

// --- Comparison ---

export interface ComparisonPeriod {
  label: string;
  metrics: Record<string, number>;
}

export interface ComparisonBlock {
  type: "comparison";
  title?: string;
  current: ComparisonPeriod;
  previous: ComparisonPeriod;
}

// --- Alert ---

export type AlertSeverity = "info" | "warning" | "danger";

export interface RelatedEntity {
  type: string;
  id: string;
  name: string;
}

export interface AlertBlock {
  type: "alert";
  severity: AlertSeverity;
  title: string;
  message: string;
  relatedEntity?: RelatedEntity;
}

// --- Text Summary ---

export interface TextSummaryBlock {
  type: "text_summary";
  content: string;
}

// --- Union type ---

export type DashboardBlock =
  | KPIGridBlock
  | LineChartBlock
  | BarChartBlock
  | DonutChartBlock
  | TableBlock
  | ComparisonBlock
  | AlertBlock
  | TextSummaryBlock;

// --- Dashboard data container ---

export interface DashboardData {
  title?: string;
  clientId?: string;
  blocks: DashboardBlock[];
}
